# Workshop 0

In [2]:
#numpy import
import numpy as np
import time

In [3]:
#empty array eith size 2X2
empty_arr = np.empty((2, 2))
empty_arr

array([[0., 0.],
       [0., 0.]])

In [4]:
#one array eith size 4X2
ones_arr = np.ones((4, 2))
print(ones_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
# Return a new array
full_arr = np.full((3, 3), 7)
print(full_arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [6]:
# New array of zeros
zeros_like_arr = np.zeros_like(ones_arr)
print(zeros_like_arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [7]:
# New array of ones with same
ones_like_arr = np.ones_like(empty_arr)
print(ones_like_arr)

[[1. 1.]
 [1. 1.]]


In [8]:
# Convert existing list to a numpy array
new_list = [1, 2, 3, 4]
converted_arr = np.array(new_list)
print(converted_arr)

[1 2 3 4]


# Array Manipulation


In [9]:
# Array with values ranging from 10 to 49
range_arr = np.arange(10, 50)
print(range_arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
# 3X3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [51]:
# 3X3 identity matrix
identity_3x3 = np.eye(3)
print(identity_3x3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# Random array of size 30 and its mean
random_arr = np.random.random(30)
print(random_arr)

[0.27288131 0.98248213 0.13680124 0.98236235 0.10074105 0.42917159
 0.79462832 0.53027334 0.26174134 0.14307973 0.29911751 0.29972591
 0.44238896 0.84525907 0.845094   0.97250255 0.97645612 0.00405332
 0.25243961 0.7324797  0.46667578 0.41012375 0.10629408 0.06802764
 0.36084812 0.73203755 0.99047024 0.74726814 0.1505558  0.22799828]


In [13]:
mean_val = random_arr.mean()
print(mean_val)

0.4854659512589464


In [14]:
# 10X10 random array with min and max
large_random = np.random.random((10, 10))
print(large_random)

[[0.6178026  0.85076247 0.42858846 0.15503873 0.70061649 0.23805253
  0.15809005 0.78539969 0.77629464 0.92214163]
 [0.90129969 0.42582403 0.23339597 0.53941311 0.07143336 0.53218905
  0.13341789 0.90079877 0.28476834 0.18408408]
 [0.67714708 0.90412275 0.65993372 0.57524566 0.08533075 0.37548309
  0.50800968 0.92289864 0.19375489 0.77298901]
 [0.7731779  0.18910955 0.92061265 0.77486724 0.02468213 0.37324918
  0.43009143 0.87815473 0.4593668  0.45580756]
 [0.78372342 0.85916265 0.55230794 0.81690129 0.59254476 0.77717758
  0.93479433 0.28037096 0.89215083 0.15842231]
 [0.47943804 0.7667885  0.52470193 0.14322248 0.02363374 0.15923198
  0.43405889 0.36094153 0.22877128 0.43838174]
 [0.11764001 0.03322651 0.34969896 0.93959383 0.66315191 0.7325954
  0.13410609 0.01242714 0.24472537 0.49015071]
 [0.13015507 0.60701472 0.67639785 0.86157634 0.34911641 0.66617379
  0.59549772 0.4912945  0.74687779 0.54987779]
 [0.0631567  0.3944762  0.47062808 0.94931967 0.05442386 0.21881069
  0.78878018 

In [15]:
min_val, max_val = large_random.min(), large_random.max()
print(min_val, max_val)

0.012427139146880761 0.9493196743939957


In [16]:
zero_vec = np.zeros(10)
print(zero_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
zero_vec[4] = 1
print(zero_vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [18]:
arr_to_reverse = np.array([1, 2, 0, 0, 4, 0])
print(arr_to_reverse)

[1 2 0 0 4 0]


In [19]:
reversed_arr = arr_to_reverse[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [20]:
border_arr = np.ones((5, 5))
print(border_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
border_arr[1:-1, 1:-1] = 0
print(border_arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
# 8X8 matrix with checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
print(checkerboard)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [23]:
checkerboard[1::2, ::2] = 1
print(checkerboard)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


In [24]:
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Array Operations

In [25]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [26]:
# Addition
add_res = np.add(x, y)
print(add_res)

[[ 6  8]
 [10 13]]


In [27]:
# Subtraction
sub_res = np.subtract(x, y)
print(sub_res)

[[-4 -4]
 [-4 -3]]


In [28]:
# Scalar multiplication
mult_res = x * 3
print(mult_res)

[[ 3  6]
 [ 9 15]]


In [29]:
# Square
square_res = np.square(x)
print(square_res)

[[ 1  4]
 [ 9 25]]


In [30]:
# Dot product
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

In [31]:
# Concatenation
concat_row = np.concatenate((x, y), axis=0)
print(concat_row)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [32]:
concat_col_vw = np.column_stack((v, w))
print(concat_col_vw)

[[ 9 11]
 [10 12]]


In [33]:
try:
    bad_concat = np.concatenate((x, v))
except ValueError as e:
    print(f"Error explanation: {e}")

Error explanation: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


# Matrix Operations

In [34]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

In [35]:
inv_A = np.linalg.inv(A)
print(inv_A)

[[-2.    1.  ]
 [ 1.75 -0.75]]


In [36]:
proof1 = np.allclose(np.dot(A, inv_A), np.eye(2))
print(proof1)

True


In [37]:
# Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
proof2 = not np.array_equal(AB, BA)

print(proof2)

True


In [38]:
proof3 = np.allclose((np.dot(A, B)).T, np.dot(B.T, A.T))
print(proof3)

True


In [39]:
coeff_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
print(coeff_matrix)

[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]


In [40]:
const_vector = np.array([-1, -3, 9])
print(const_vector)

[-1 -3  9]


In [41]:
solution = np.linalg.solve(coeff_matrix, const_vector)
print(solution)

[ 2.  1. -2.]


# How fast numpy is?

In [42]:
size = 1000000

In [43]:
list_a = list(range(size))
list_b = list(range(size))
array_a = np.arange(size)
array_b = np.arange(size)

In [44]:
start_time = time.time()
result_list = [list_a[i] + list_b[i] for i in range(size)]
python_add_time = time.time() - start_time
print(f"Python List Addition: {python_add_time:.5f} seconds")

Python List Addition: 0.06429 seconds


In [45]:
start_time = time.time()
result_array = array_a + array_b
numpy_add_time = time.time() - start_time
print(f"NumPy Array Addition: {numpy_add_time:.5f} seconds")

NumPy Array Addition: 0.00244 seconds


In [46]:
# Python List Multiplication
start_time = time.time()
result_list = [list_a[i] * list_b[i] for i in range(size)]
python_mul_time = time.time() - start_time
print(f"Python List Multiplication: {python_mul_time:.5f} seconds")

Python List Multiplication: 0.06561 seconds


In [47]:
# NumPy Array Multiplication
start_time = time.time()
result_array = array_a * array_b
numpy_mul_time = time.time() - start_time
print(f"NumPy Array Multiplication: {numpy_mul_time:.5f} seconds")

NumPy Array Multiplication: 0.00153 seconds


In [48]:
# Python List Dot Product
start_time = time.time()
dot_product_list = sum(list_a[i] * list_b[i] for i in range(size))
python_dot_time = time.time() - start_time
print(f"Python List Dot Product: {python_dot_time:.5f} seconds")

Python List Dot Product: 0.06392 seconds


In [49]:
# NumPy Array Dot Product
start_time = time.time()
dot_product_array = np.dot(array_a, array_b)
numpy_dot_time = time.time() - start_time
print(f"NumPy Array Dot Product: {numpy_dot_time:.5f} seconds")

NumPy Array Dot Product: 0.00048 seconds


In [50]:
matrix_size = 1000
mat_a = np.random.rand(matrix_size, matrix_size)
mat_b = np.random.rand(matrix_size, matrix_size)
list_mat_a = mat_a.tolist()
list_mat_b = mat_b.tolist()

# NumPy Matrix Multiplication
start_time = time.time()
result_numpy_mat = np.matmul(mat_a, mat_b)
numpy_mat_time = time.time() - start_time
print(f"NumPy Matrix Multiplication: {numpy_mat_time:.5f} seconds")


NumPy Matrix Multiplication: 0.01215 seconds
